apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo-ms-post-service
  labels:
    environment: production
spec:
  selector:
    matchLabels:
      app: post-service
  replicas: 1
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: demo-ms-post-service
          image: post_service
          ports:
            - containerPort: 1332
