apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: post-service
  namespace: demo-micro-service-development
  labels:
    app: post-service
spec:
  selector:
    matchLabels:
      app: post-service
  replicas: 1
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: post_service
          ports:
            - containerPort: 1332
